dependencies {
    implementation "org.xerial:sqlite-jdbc:3.44.1.0"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "org.slf4j:slf4j-api:${slf4jVersion}"

    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "ch.qos.logback:logback-classic:${logbackVersion}"
}
