package com.lightweightai.plugin.example;

import com.lightweightai.kernel.agent.Tool;
import com.lightweightai.kernel.agent.ToolSchema;
import com.lightweightai.kernel.llm.ToolResult;

import java.util.Map;

/**
 * 示例插件工具：打招呼
 *
 * 演示如何通过实现 Tool 接口创建可被 DynamicPluginProvider 热加载的工具。
 */
public class GreetTool implements Tool {

    @Override
    public String getName() {
        return "greet";
    }

    @Override
    public String getDescription() {
        return "Greet someone by name. Use this tool when the user wants to say hello to someone.";
    }

    @Override
    public ToolSchema getSchema() {
        return new ToolSchema(Map.of(
            "type", "object",
            "properties", Map.of(
                "name", Map.of(
                    "type", "string",
                    "description", "The name of the person to greet"
                )
            )
        ));
    }

    @Override
    public ToolResult execute(Map<String, Object> args) {
        String name = (String) args.getOrDefault("name", "World");
        String greeting = String.format("Hello, %s! Welcome to the AI Agent platform. " +
            "This greeting was generated by a dynamically loaded plugin. 🎉", name);
        return ToolResult.success("greet", greeting);
    }
}
